//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.11.29 at 02:08:09 PM MSK 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://student.example.com/generatedXml", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.example.student.generatedxml;
